[package]
name = "bch"
version = "0.1.0"
authors = ["sbaginsk <szymon.baginski@gmail.com>"]
edition = "2018"

[dependencies]
bitvec = "0.9"
env_logger = "0.6"
log = "0.4"
primes = "0.2"
itertools = "0.8"
